name: Update Playwright Snapshots

on:
  workflow_dispatch:
permissions:
  # Give the default GITHUB_TOKEN write permission to commit and push
  contents: write

jobs:
  update-snapshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create .env file
        run: |
          touch .env
          echo "${{secrets.TEST_SECRETS}}" >> .env
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Cache npm
        uses: actions/cache@v4
        with:
          path: '~/.npm'
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Install dependencies
        run: npm install --legacy-peer-deps
      - name: Restore Playwright binaries cache
        uses: actions/cache@v4
        id: playwright-cache
        with:
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/playwright.config.ts') }}
          path: ~/.cache/ms-playwright
          restore-keys: |
            ${{ runner.os }}-playwright-${{ hashFiles('**/playwright.config.ts') }}
            ${{ runner.os }}-playwright-
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        if: steps.playwright-cache.outputs.cache-hit != 'true'
      - name: Update Playwright snapshots
        run: npx playwright test --update-snapshots
      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Commit and push updated snapshots
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'updated snapshots'
